version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]
  style_guide = "airbnb"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
