apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efh-web
  namespace: efh-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - elevateconnectsdirectory.org
      secretName: efh-tls
  rules:
    - host: elevateconnectsdirectory.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: efh-web
                port:
                  number: 80
