apiVersion: v1
kind: Service
metadata:
  name: efh-web
  namespace: efh-prod
  labels:
    app: efh-web
spec:
  type: ClusterIP
  selector:
    app: efh-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
