grafana:
  adminUser: admin
  adminPassword: change-me-in-production
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.elevateconnectsdirectory.org
    tls:
      - secretName: efh-grafana-tls
        hosts:
          - grafana.elevateconnectsdirectory.org

prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.elevateconnectsdirectory.org
    tls:
      - secretName: efh-prometheus-tls
        hosts:
          - prometheus.elevateconnectsdirectory.org
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.elevateconnectsdirectory.org
    tls:
      - secretName: efh-alertmanager-tls
        hosts:
          - alertmanager.elevateconnectsdirectory.org
